docs/AboutUs.md
=> Add Alex's details to AboutUs Page

docs/AboutUs.md
=> Edit AboutUs details for Nicholas

docs/AboutUs.md
Reverts AY2425S1-CS2103T-T08-1/tp#18
=> Revert "Update AboutUs.md"

docs/AboutUs.md
=> Add Tze Zhao's Details to About Page

README.md, docs/AboutUs.md, docs/UserGuide.md
=> Removes traces of AB3 from README.md and AboutUs.md

src/main/java/seedu/address/model/addresses/BtcAddress.java, src/main/java/seedu/address/model/addresses/Network.java, src/main/java/seedu/address/model/addresses/PublicAddress.java, src/main/java/seedu/address/model/person/Person.java
=> Add support for public addresses to Person model

src/main/java/seedu/address/model/util/SampleDataUtil.java
=> Add function for getting tags for cryptocurrencies

src/main/java/seedu/address/logic/commands/EditCommand.java, src/main/java/seedu/address/logic/parser/CliSyntax.java
=> Logic: Add placeholder address field and message usage example

src/main/java/seedu/address/model/addresses/PublicAddressFactory.java, src/main/java/seedu/address/model/person/Person.java, src/main/java/seedu/address/model/util/SampleDataUtil.java, src/main/java/seedu/address/storage/JsonAdaptedPerson.java, src/main/java/seedu/address/storage/JsonAdaptedPublicAddress.java, src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json, src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java, src/test/java/seedu/address/testutil/PersonBuilder.java, src/test/java/seedu/address/testutil/TypicalPersons.java
=> Support persisting of public addresses

src/main/java/seedu/address/logic/Messages.java, src/main/java/seedu/address/logic/commands/RetrievePublicAddressCommand.java, src/main/java/seedu/address/logic/parser/AddressBookParser.java, src/main/java/seedu/address/logic/parser/CliSyntax.java, src/main/java/seedu/address/logic/parser/ParserUtil.java, src/main/java/seedu/address/logic/parser/RetrievePublicAddressCommandParser.java, src/main/java/seedu/address/model/addresses/Network.java, src/main/java/seedu/address/model/addresses/PublicAddress.java, src/main/java/seedu/address/storage/JsonAdaptedPublicAddress.java, src/test/java/seedu/address/logic/commands/RetrievePublicAddressCommandTest.java, src/test/java/seedu/address/logic/parser/RetrievePublicAddressCommandParserTest.java, src/test/java/seedu/address/testutil/TypicalPersons.java
=> 64 add command for retrieving all public addresses on network

src/main/java/seedu/address/logic/commands/RetrievePublicAddressCommand.java, src/main/java/seedu/address/logic/parser/CliSyntax.java, src/main/java/seedu/address/logic/parser/ParserUtil.java, src/main/java/seedu/address/logic/parser/RetrievePublicAddressCommandParser.java, src/main/java/seedu/address/model/addresses/PublicAddress.java, src/main/java/seedu/address/storage/JsonAdaptedPublicAddress.java, src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json, src/test/java/seedu/address/logic/commands/RetrievePublicAddressCommandTest.java, src/test/java/seedu/address/logic/parser/RetrievePublicAddressCommandParserTest.java, src/test/java/seedu/address/testutil/PersonBuilder.java, src/test/java/seedu/address/testutil/TypicalPersons.java
=> Standardise naming and clean up public addresses in storage layer

src/main/java/seedu/address/logic/commands/SearchPublicAddressCommand.java, src/main/java/seedu/address/logic/parser/RetrievePublicAddressCommandParser.java, src/main/java/seedu/address/logic/parser/SearchPublicAddressCommandParser.java, src/test/java/seedu/address/logic/parser/CommandParserTestUtil.java, src/test/java/seedu/address/logic/parser/SearchPublicAddressCommandParserTest.java
Fixes #90. Added more test cases for parser.
=> Feature: add more test cases for SearchPublicAddressCommandParserTest

src/main/java/seedu/address/logic/commands/DeletePublicAddressCommand.java, src/main/java/seedu/address/logic/parser/DeletePublicAddressCommandParser.java, src/main/java/seedu/address/logic/parser/ParserUtil.java, src/main/java/seedu/address/model/person/Person.java, src/test/java/seedu/address/logic/commands/DeletePublicAddressCommandTest.java, src/test/java/seedu/address/logic/parser/DeletePublicAddressCommandParserTest.java, src/test/java/seedu/address/logic/parser/ParserUtilTest.java
=> Add DeletePublicAddress by Specific Labels

src/main/java/seedu/address/logic/commands/RetrievePublicAddressCommand.java, src/main/java/seedu/address/logic/parser/RetrievePublicAddressCommandParser.java, src/test/java/seedu/address/logic/parser/RetrievePublicAddressCommandParserTest.java
=> Change PREFIX from pa/ to c/ for retrievePublicAddress

src/main/java/seedu/address/logic/parser/ParserUtil.java, src/main/java/seedu/address/model/addresses/BtcAddress.java, src/main/java/seedu/address/model/addresses/EthAddress.java, src/main/java/seedu/address/model/addresses/PublicAddress.java, src/main/java/seedu/address/model/addresses/PublicAddressFactory.java, src/main/java/seedu/address/model/addresses/SolAddress.java, src/main/java/seedu/address/storage/JsonAdaptedPublicAddress.java, src/test/java/seedu/address/model/addresses/BtcAddressTest.java, src/test/java/seedu/address/model/addresses/EthAddressTest.java, src/test/java/seedu/address/model/addresses/PublicAddressFactoryTest.java, src/test/java/seedu/address/model/addresses/PublicAddressTest.java, src/test/java/seedu/address/model/addresses/SolAddressTest.java, src/test/java/seedu/address/storage/JsonAdaptedPublicAddressTest.java
=> Add public address validation for different network types

src/main/java/seedu/address/logic/commands/AbstractEditCommand.java
Update AbstractEditCommand to accept custom bifunctions for creating an edited person
=> Logic: Create functional interface for creating edited persons

src/main/java/seedu/address/logic/commands/EditPublicAddressCommand.java, src/main/java/seedu/address/logic/parser/AddressBookParser.java, src/main/java/seedu/address/logic/parser/EditPublicAddressCommandParser.java, src/main/java/seedu/address/model/person/Person.java, src/test/java/seedu/address/logic/commands/EditPublicAddressCommandTest.java, src/test/java/seedu/address/logic/parser/AddressBookParserTest.java, src/test/java/seedu/address/logic/parser/EditPublicAddressCommandParserTest.java, src/test/java/seedu/address/model/person/PersonTest.java
=> Add editPublicAddress command for editing specific public addresses

src/main/java/seedu/address/logic/commands/AbstractEditCommand.java, src/main/java/seedu/address/logic/commands/AddPublicAddressCommand.java, src/main/java/seedu/address/logic/parser/AddPublicAddressCommandParser.java, src/main/java/seedu/address/logic/parser/AddressBookParser.java, src/main/java/seedu/address/logic/parser/ParserUtil.java, src/test/java/seedu/address/logic/commands/AddPublicAddressCommandTest.java, src/test/java/seedu/address/logic/parser/AddPublicAddressCommandParserTest.java, src/test/java/seedu/address/logic/parser/AddressBookParserTest.java, src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
Creates a new command for the addition of public addresses to an existing person.
Fixes #24, #96, #99
=> Public address addition

docs/UserGuide.md, src/main/java/seedu/address/logic/commands/RetrievePublicAddressCommand.java
=> Update user guide for editpa and retrievepa commands

src/main/java/seedu/address/ui/PersonCard.java, src/main/resources/view/DarkTheme.css, src/main/resources/view/PersonListCard.fxml
Fixes #82 
Still in the process of #94
=> Improve UI for readability

docs/UserGuide.md, src/main/java/seedu/address/logic/commands/SearchPublicAddressCommand.java
=> Enhance User Guide and fix consistency issues

README.md, docs/.gitignore, src/main/java/seedu/address/logic/Messages.java, src/main/java/seedu/address/logic/commands/AbstractEditCommand.java, src/main/java/seedu/address/logic/commands/AddPublicAddressCommand.java, src/main/java/seedu/address/logic/commands/DeletePublicAddressCommand.java, src/main/java/seedu/address/logic/commands/EditPublicAddressCommand.java, src/main/java/seedu/address/logic/commands/SearchPublicAddressCommand.java, src/main/java/seedu/address/logic/parser/AddCommandParser.java, src/main/java/seedu/address/logic/parser/AddPublicAddressCommandParser.java, src/main/java/seedu/address/logic/parser/EditCommandParser.java, src/main/java/seedu/address/logic/parser/ParserUtil.java, src/main/java/seedu/address/model/addresses/PublicAddressFactory.java, src/main/java/seedu/address/model/addresses/PublicAddressesComposition.java, src/main/java/seedu/address/model/person/Person.java, src/main/java/seedu/address/model/util/SampleDataUtil.java, src/main/java/seedu/address/storage/JsonAdaptedPerson.java, src/main/java/seedu/address/ui/PersonCard.java, src/test/java/seedu/address/logic/commands/AddPublicAddressCommandTest.java, src/test/java/seedu/address/logic/commands/CommandTestUtil.java, src/test/java/seedu/address/logic/commands/DeletePublicAddressCommandTest.java, src/test/java/seedu/address/logic/commands/EditCommandTest.java, src/test/java/seedu/address/logic/commands/EditPublicAddressCommandTest.java, src/test/java/seedu/address/logic/parser/AddressBookParserTest.java, src/test/java/seedu/address/logic/parser/ParserUtilTest.java, src/test/java/seedu/address/model/person/PersonTest.java, src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java, src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java, src/test/java/seedu/address/testutil/PersonBuilder.java
=> Refactor Map<Network,Set<PublicAddress>> to PublicAddressesComposition

src/main/java/seedu/address/logic/commands/FilterByNetworkCommand.java, src/main/java/seedu/address/logic/parser/AddressBookParser.java, src/main/java/seedu/address/logic/parser/FilterByNetworkCommandParser.java, src/test/java/seedu/address/logic/commands/FilterByNetworkCommandTest.java, src/test/java/seedu/address/logic/parser/FilterByNetworkCommandParserTest.java
=> Add Command for Filter By Networks

src/main/java/seedu/address/logic/commands/DeletePublicAddressCommand.java, src/main/java/seedu/address/logic/parser/DeletePublicAddressCommandParser.java, src/main/java/seedu/address/model/addresses/PublicAddressesComposition.java, src/main/java/seedu/address/model/person/Person.java, src/test/java/seedu/address/logic/commands/DeletePublicAddressCommandTest.java, src/test/java/seedu/address/logic/commands/RetrievePublicAddressCommandTest.java, src/test/java/seedu/address/logic/parser/DeletePublicAddressCommandParserTest.java, src/test/java/seedu/address/model/person/PersonTest.java
Fixes #135 and #121 
commit [a7d1f48](https://github.com/AY2425S1-CS2103T-T08-1/tp/pull/145/commits/a7d1f4833254b7ad7ccee4d0de179fbf3b6bdcfe) fixes #146
=> Refactor DeletePublicAddressCommand

src/main/java/seedu/address/logic/commands/AddPublicAddressCommand.java, src/main/java/seedu/address/model/addresses/PublicAddressesComposition.java, src/main/java/seedu/address/model/person/Person.java, src/main/java/seedu/address/storage/JsonAdaptedPerson.java, src/test/java/seedu/address/logic/commands/AddPublicAddressCommandTest.java, src/test/java/seedu/address/logic/commands/DeletePublicAddressCommandTest.java, src/test/java/seedu/address/logic/parser/ParserUtilTest.java, src/test/java/seedu/address/model/person/PersonTest.java, src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
=> Validation for unique label within a person's network

src/main/java/seedu/address/logic/commands/AddCommand.java, src/main/java/seedu/address/logic/commands/EditCommand.java, src/main/java/seedu/address/logic/parser/AddCommandParser.java, src/main/java/seedu/address/logic/parser/EditCommandParser.java, src/main/java/seedu/address/logic/parser/ParserUtil.java, src/test/java/seedu/address/logic/parser/ParserUtilTest.java
=> Revert add and edit commands

docs/UserGuide.md, src/main/java/seedu/address/logic/commands/RetrievePublicAddressCommand.java, src/main/java/seedu/address/logic/parser/RetrievePublicAddressCommandParser.java, src/main/java/seedu/address/model/addresses/PublicAddressesComposition.java, src/main/java/seedu/address/model/person/Person.java, src/test/java/seedu/address/logic/commands/CommandTestUtil.java, src/test/java/seedu/address/logic/commands/FilterByNetworkCommandTest.java, src/test/java/seedu/address/logic/commands/RetrievePublicAddressCommandTest.java, src/test/java/seedu/address/logic/parser/RetrievePublicAddressCommandParserTest.java, src/test/java/seedu/address/testutil/TypicalPersons.java
=> Add support for search without index for retrievepa

docs/UserGuide.md
=> [Bug] UG Incorrect tip regarding command case sensitivity

src/main/java/seedu/address/logic/commands/FilterByNetworkCommand.java
=> Improve filter function to show the person's index

src/main/java/seedu/address/logic/commands/EditPublicAddressCommand.java, src/main/java/seedu/address/logic/parser/EditPublicAddressCommandParser.java, src/main/java/seedu/address/model/addresses/BtcAddress.java, src/main/java/seedu/address/model/addresses/EthAddress.java, src/main/java/seedu/address/model/addresses/PublicAddressFactory.java, src/main/java/seedu/address/model/addresses/SolAddress.java, src/test/java/seedu/address/logic/commands/EditPublicAddressCommandTest.java, src/test/java/seedu/address/logic/parser/AddressBookParserTest.java, src/test/java/seedu/address/logic/parser/EditPublicAddressCommandParserTest.java, src/test/java/seedu/address/testutil/TypicalPersons.java
=> [Bug] editpa allows spaces in public addresses

src/main/java/seedu/address/logic/parser/AddPublicAddressCommandParser.java, src/main/java/seedu/address/logic/parser/ArgumentTokenizer.java, src/main/java/seedu/address/logic/parser/CliSyntax.java, src/main/java/seedu/address/logic/parser/EditPublicAddressCommandParser.java
=> [BUG] Incorrect error message show when editing a public address with additional wrong prefixes

src/main/java/seedu/address/model/addresses/Network.java
=> Widen network error message

docs/DeveloperGuide.md, docs/UserGuide.md, src/main/resources/view/MainWindow.fxml
Fixes #194, #201, #203, #204, #207, #208, #210, #213, #223, #229, #231, #234, #239, #242, #244, #246, #251, #257,  #259, #262, #263
=> Improve User Guide

docs/site.json
=> Remove reference to AB3 in documentation titles

src/main/java/seedu/address/logic/commands/AddPublicAddressCommand.java, src/main/java/seedu/address/model/addresses/BtcAddress.java, src/main/java/seedu/address/model/addresses/EthAddress.java, src/main/java/seedu/address/model/addresses/PublicAddress.java, src/main/java/seedu/address/model/addresses/SolAddress.java, src/test/java/seedu/address/logic/parser/EditPublicAddressCommandParserTest.java
=> Remove / resolve todos in code base
